title: "Duong Vu"
author: "Duong Vu"
description: "This page is under construction"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.html"}
  - {title: "About me", file: "aboutme.md"}
  - {title: "Projects", icon: github, url: "https://github.com/vuthuyduong"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:duong.t.vu@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/vuthuyduong"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/Duong_Thuy_Vu"}
  - {title: Google scholar, icon: google, url: "https://scholar.google.com/citations?user=ugNE8zUAAAAJ&hl=en"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Duong-Vu-43"}
  - {title: Orcid, icon: orcid, url: "https://orcid.org/0000-0001-7960-2765"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/duong-vu-9a6b3bb7/?originalSubdomain=nl"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
